# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: WBMonstr
email: wbmonstr@gmail.com
tagline: Blending Art, Creativity & Code be Awesome
keyword: "template wordpress, branding dengan website, seo, jasa pembuatan website, web usaha, website ukm, web design, web design di bali, web designer bali, company profile, bali web design, web design bali, design web bali"
description: > # this means to ignore newlines until "baseurl:"
  Kita bisa bantu kamu untuk membangun website dengan pendekatan bergaya modern yang sedang ngtren saat ini. Nantinya bisa kamu jadikan sebagai sarana perkenalan produk dan usahamu. Cocok banget buat kamu yang muda-muda baru membuka usaha.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wbmonstr.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
telephone: 089685585336

port: 3900

permalink: /:title.html

sass:
  sass_dir: css/_sass

# Build settings
markdown: kramdown